# Generated by Django 4.2.7 on 2023-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_subscribe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.IntegerField(choices=[(0, 'dark'), (1, 'light')], default=0),
        ),
    ]
