# Generated by Django 4.2.7 on 2023-12-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='word_count',
        ),
        migrations.AddField(
            model_name='chapter',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
